# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preseed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preseedinstance',
            name='network_type',
            field=models.CharField(choices=[('dhcp', 'DHCP'), ('static', 'STATIC')], default='static', max_length=6),
        ),
    ]
