# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('preseed', '0003_auto_20171015_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='preseedinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preseedinstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
