# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preseed', '0005_preseedinstance_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='preseedinstance',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preseedinstance',
            name='root_password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preseedinstance',
            name='user_password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='preseedinstance',
            name='user_ssh_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='preseedinstance',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='preseedinstance',
            name='ntp_server',
            field=models.CharField(default='pool.ntp.org', max_length=100),
        ),
    ]
