# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preseed', '0007_auto_20171111_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preseedinstance',
            name='apps',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
